dataset:
    root_dir: ''
    image_height: 128
    image_width: 416
    min_depth: 0.1
    max_depth: 100.
    preprocess: True
model:
    root_dir: ''
    learning_rate: 1e-4
    batch_size: 12
    num_source: 3
    num_scales: 4
    epoch: 30
    beta1: 0.9
    reproj_alpha: 0.85
    smooth_alpha: 1e-3
    batch_norm_decay: 0.95
    batch_norm_epsilon: 1e-5
    pose_scale: 1e-2
    continue_ckpt: ''
    summary_freq: 200